CREATE OR REPLACE PROCEDURE INSERT_DEPARTMENTSE AS
BEGIN
  FOR rec IN (
    SELECT DISTINCT R.DEPARTMENT_ID, R.COURSES_ID, R.SCHEDULE
    FROM REGISTRATION R
    LEFT JOIN DEPARTMENTS_COURSES DC ON R.DEPARTMENT_ID = DC.DEPARTMENT_ID AND R.COURSES_ID = DC.COURSES_ID
    WHERE DC.DEPARTMENT_ID IS NULL
  )
  LOOP
    BEGIN
      INSERT INTO DEPARTMENTS_COURSES (DEPARTMENT_ID, COURSES_ID, SCHEDULE)
      VALUES (rec.DEPARTMENT_ID, rec.COURSES_ID, rec.SCHEDULE);
    EXCEPTION
      WHEN DUP_VAL_ON_INDEX THEN
        NULL; 
    END;
  END LOOP;
END;
/

BEGIN
  INSERT_DEPARTMENTSE;
END;
/
